// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrGTSoJYmsq3ScG7bc2WlSnFfs2HvPwug',
    appId: '1:210460821990:web:3896f1d7edb95b80732e27',
    messagingSenderId: '210460821990',
    projectId: 'goodle-cdb2a',
    authDomain: 'goodle-cdb2a.firebaseapp.com',
    storageBucket: 'goodle-cdb2a.appspot.com',
    measurementId: 'G-R4P2W45RBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLSpt9CTLTdNYDUi9zpe8FQSvZXoU3Dqo',
    appId: '1:210460821990:android:a7f3cf63b22e47db732e27',
    messagingSenderId: '210460821990',
    projectId: 'goodle-cdb2a',
    storageBucket: 'goodle-cdb2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLZ8dHuDVqGCR5oZjQxysp8vU9oAfgJU',
    appId: '1:210460821990:ios:7272faa2634d77be732e27',
    messagingSenderId: '210460821990',
    projectId: 'goodle-cdb2a',
    storageBucket: 'goodle-cdb2a.appspot.com',
    iosClientId: '210460821990-iu2ib50s7c3ppj7pb66ss66kk8bj3trv.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodly',
  );
}
